import tempfile
import bs4
from fastapi.responses import FileResponse
from markdown import markdown
from weasyprint import HTML

# A function to prepare input data for diabetes risk score model
def prepare_for_diagnosis(family_history, bmi, age, waist_to_hip_ratio, physical_activity, alcohol_consumption_per_week):
    age_30_39 = 1 if 30 <= age <= 39 else 0
    age_40_49 = 1 if 40 <= age <= 49 else 0
    age_50_59 = 1 if 50 <= age <= 59 else 0
    age_60_69 = 1 if 60 <= age <= 69 else 0
    age_70_79 = 1 if 70 <= age <= 79 else 0
    age_80_plus = 1 if age >= 80 else 0

    physical_activity_Moderate = 1 if 100 <= physical_activity < 150 else 0
    physical_activity_Active = 1 if 150 <= physical_activity < 300 else 0
    physical_activity_Very_Active = 1 if physical_activity >= 300 else 0

    bmi_Normal = 1 if 18.5 <= bmi < 25 else 0
    bmi_Overweight = 1 if 25 <= bmi < 30 else 0
    bmi_Obese_I = 1 if 30 <= bmi < 35 else 0
    bmi_Obese_II = 1 if 35 <= bmi < 40 else 0

    alcohol_consumption_per_week_Light = 1 if 0 < alcohol_consumption_per_week <= 3 else 0
    alcohol_consumption_per_week_Moderate = 1 if 3 < alcohol_consumption_per_week <= 7 else 0
    alcohol_consumption_per_week_Heavy = 1 if (7 < alcohol_consumption_per_week) and (alcohol_consumption_per_week != 0) else 0

    input_data = [[family_history, age_30_39, age_40_49, age_50_59, age_60_69, age_70_79, age_80_plus, physical_activity_Moderate, physical_activity_Active, physical_activity_Very_Active, bmi_Normal, bmi_Overweight, bmi_Obese_I, bmi_Obese_II, waist_to_hip_ratio, alcohol_consumption_per_week_Light, alcohol_consumption_per_week_Moderate, alcohol_consumption_per_week_Heavy]]

    return input_data

# A function to generate a PDF report from the LLM's explanation
def generate_pdf_report(explanation: str, title: str) -> FileResponse:
    # --- Convert LLM Markdown output to HTML ---
    html_body = markdown(
        explanation,
        extensions=["extra", "sane_lists", "smarty"]
    )

    soup = bs4.BeautifulSoup(html_body, "html.parser")

    clean_html_body = ""
    for el in soup.contents:
        if el.name is None:  # raw text
            text = el.strip()
            if text:
                clean_html_body += f"<p>{text}</p>"
        else:
            clean_html_body += str(el)

    # --- Create a styled HTML template for the PDF ---
    html_template = f"""
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body {{
                font-family: "Helvetica", sans-serif;
                margin: 40px 55px;
                color: #333;
                line-height: 1.6;
            }}

            h1, h2, h3 {{
                color: #1A5276;
                margin-top: 25px;
                margin-bottom: 10px;
            }}

            h1 {{
                font-size: 28px;
            }}

            h2 {{
                font-size: 22px;
            }}

            p {{
                font-size: 12pt;
                margin-bottom: 12px;
            }}

            ul {{
                margin-bottom: 15px;
                margin-left: 20px;
            }}

            li {{
                margin: 6px 0;
            }}

            .footer {{
                margin-top: 40px;
                text-align: center;
                font-size: 10pt;
                color: #888;
            }}

            .header-title {{
                text-align: center;
                font-size: 30px;
                color: #154360;
                margin-bottom: 40px;
            }}

            hr {{
                margin-top: 20px;
                margin-bottom: 20px;
            }}
        </style>
    </head>
    <body>

    <div class="header-title">{title}</div>

    <hr/>

    {html_body}

    <div class="footer">
        · Generated by gpt-5-mini, based on your input and our model's predictions ·
    </div>

    </body>
    </html>
    """

    # --- Generate PDF using WeasyPrint ---
    pdf_file = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    HTML(string=html_template).write_pdf(pdf_file.name)

    # --- Return PDF ---
    return FileResponse(
        path=pdf_file.name,
        media_type="application/pdf",
        filename="risk_report.pdf"
    )